logging:
  level:
    ru:
      liga: TRACE
  file:
    name: logs/app.log
    max-size: 10MB
    max-backup: 10
  console:
    level: TRACE

database:
  url: jdbc:postgresql://localhost:5432/parcels_db
  username: admin
  password: 123
  driverClassName: org.postgresql.Driver

spring:
  data:
    jpa:
      hibernate:
        ddl-auto: update
  datasource:
    url: ${database.url}
    username: ${database.username}
    password: ${database.password}
    driverClassName: ${database.driverClassName}

flyway:
  locations: classpath:db/migration
  url: ${database.url}
  user: ${database.username}
  password: ${database.password}
  schemas: parcels